In [1]:
"""
날짜 : 2020/08/10
이름 : 최정한
내용 : Numpy(수치해석 패키지) 실습하기
"""

'\n날짜 : 2020/08/10\n이름 : 최정한\n내용 : Numpy(수치해석 패키지) 실습하기\n'

In [3]:
import numpy as np

In [6]:
#벡터생성
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [10]:
v2 = np.arange(5)
v2

array([0, 1, 2, 3, 4])

In [13]:
#0 -1 사이 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.74645822, 0.24151408, 0.65569355, 0.3453368 , 0.63521749,
       0.43718144, 0.14338708, 0.81029712, 0.97127024, 0.22423095,
       0.4864085 , 0.02242088, 0.7070326 , 0.29248774, 0.79543051,
       0.38651169, 0.34965665, 0.78064219, 0.48891575, 0.51262218,
       0.58608794, 0.25527759, 0.37044269, 0.88562933, 0.42656201,
       0.67185036, 0.01060613, 0.37155674, 0.55600806, 0.4508697 ,
       0.04107126, 0.48652225, 0.52085692, 0.55568977, 0.39619177,
       0.29970962, 0.97073617, 0.49688578, 0.9082848 , 0.87313666,
       0.36111244, 0.23388077, 0.32969502, 0.61124869, 0.93136905,
       0.19985809, 0.73216246, 0.7201476 , 0.43324041, 0.95092488,
       0.1036854 , 0.18517195, 0.85777666, 0.72920926, 0.94946669,
       0.59958527, 0.32561336, 0.69616014, 0.14351318, 0.2116953 ,
       0.95718408, 0.90867512, 0.05587844, 0.73064455, 0.79271081,
       0.19684205, 0.09641165, 0.28086242, 0.05140003, 0.07423867,
       0.0166837 , 0.3772738 , 0.36340517, 0.17178491, 0.91926

In [15]:
#표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-0.01507671,  0.02313338,  0.13995098, -1.48863385,  0.09804269,
       -0.27466158,  0.28351956,  0.58683068,  0.62846849, -1.12633066,
       -0.37071906, -0.11313046, -2.34767272,  0.7210965 , -1.1733563 ,
        2.20960847, -0.63252491,  0.8191958 , -0.57161011, -1.0170526 ,
        0.77307412,  0.04604379,  0.78793085,  0.31818753,  1.41963272,
        2.03469627,  0.46395664,  1.04978132, -0.42149369,  0.26155528,
       -1.24656009,  0.83820796,  1.69894176, -0.61349034, -0.15549495,
        0.36152014, -1.02222985,  0.91361024,  0.23527913,  0.52176866,
       -0.39690467, -1.13779666,  1.57557636, -0.15238467, -1.08411065,
        0.23064914, -0.70369103, -0.43346764,  0.56346473, -0.94123021,
       -1.04425321, -0.53671854,  0.796174  , -0.97005727, -1.29199172,
        0.44725686,  0.70510384, -1.91534116, -1.8757099 ,  0.27057708,
       -0.6768931 , -0.18817089,  0.37736656, -0.58034379, -0.51287205,
        0.85327504, -0.53089161, -1.49660404, -0.54918929,  0.18

In [16]:
#평균 0, 표준편차가 1인 정규분포를 따르는 임의의 실수 100개
rand3 = np.random.normal(0, 1, 100)
rand3

array([ 0.43292473,  1.11735858, -0.82061748,  0.82182307,  0.23586629,
       -1.83168214,  0.56671027, -0.27025154, -1.24209294,  0.51156397,
       -1.06773524,  1.19588932, -1.36043537,  1.70393108, -2.4418929 ,
        0.60378746, -1.15492325, -0.27804576, -2.23972446, -1.17424027,
       -1.51753401,  0.30842754, -0.74623546,  0.27122331, -0.54380797,
        0.81205575,  0.67598844,  1.25340905, -0.67560335,  0.78389794,
        3.32276046,  1.17147488,  1.29962385, -0.38800933, -0.79740429,
       -0.55979275,  0.17163673, -1.72953097,  0.98574986, -0.79461389,
       -1.55040369,  0.01800964, -0.92419841, -1.14622754, -1.39561248,
       -0.62895554,  0.58864219,  0.84703592,  1.38741993,  0.14158102,
        1.1768357 ,  0.6495749 , -0.56981093, -1.36819275,  1.58337805,
        0.11125936, -1.54056546, -0.40821937, -0.39392946, -0.81497304,
        0.58059733,  0.85745013,  1.08789968, -0.21713756,  0.51381769,
        0.29876897, -0.75827667, -0.48043365, -1.90811338, -1.34